export const createReimbursementTypes = {
  CREATE_REIMBURSEMENT: 'CREATE_REIMBURSEMENT',
  UPDATE_AMOUNT: 'UPDATE_AMOUNT',
  UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
  UPDATE_ERROR: 'UPDATE_ERROR',
  UPDATE_TYPE: 'UPDATE_TYPE'
}