export const reimbursementTableTypes = {
    FETCH_REIMBURSEMENTS: 'FETCH_REIMBURSEMENTS',
    FILTER_REIMBURSEMENTS: 'FILTER_REIMBURSEMENTS',
    UPDATE_ACTIVE_PAGE: 'UPDATE_ACTIVE_PAGE',
    UPDATE_CUSTOM_ITEMS_COUNT_PER_PAGE: 'UPDATE_CUSTOM_ITEMS_COUNT_PER_PAGE',
    UPDATE_DETAILS_SHOWN: 'UPDATE_DETAILS_SHOWN',
    UPDATE_ITEMS_COUNT_PER_PAGE: 'UPDATE_ITEMS_COUNT_PER_PAGE',
    UPDATE_REIMBURSEMENT: 'UPDATE_REIMBURSEMENT',
    UPDATE_USERNAME_FILTER: 'UPDATE_USERNAME_FILTER'
}