export const reimbursementTableTypes = {
    FETCH_REIMBURSEMENTS: 'FETCH_REIMBURSEMENTS',
    FILTER_REIMBURSEMENTS: 'FILTER_REIMBURSEMENTS',
    UPDATE_ACTIVE_PAGE: 'UPDATE_ACTIVE_PAGE',
    UPDATE_ITEM_COUNTS_PER_PAGE: 'UPDATE_ITEM_COUNTS_PER_PAGE',
    UPDATE_REIMBURSEMENT: 'UPDATE_REIMBURSEMENT'
}